# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - '*/**.js'
      - '*/**.vue'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2

      - name: Install dependencies
        run: npm ci

      #- name: Run CI checks
      #  run: make ci

      #- name: Run tests
      #  run: npm run tests

      - name: Run test build
        run: make build

  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2

      - run: git config user.email "robot@github.actions"
      - run: git config user.name "CI"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - run: echo "image=ghcr.io/tuuturu/news" >> $GITHUB_ENV
      - run: echo "version=$(npm version patch | sed 's/^.//')" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: docker build --tag ${{ env.image }}:${{ env.version }} .

      - name: Push docker image
        run: docker push ${{ env.image }}:${{ env.version }}


      - run: git reset HEAD~1 # Needed for commit version bump to find the changes for some reason

      - run: |
          sed -i 's~${{ env.image }}:.*~${{ env.image }}:${{ env.version }}~' \
          kustomize/deployment.yaml

      - name: Commit version bump
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 'Automated Version Bump'
          author_email: 'action@github.com'
          add: 'package.json package-lock.json kustomize/deployment.yaml'
          message: "📦 Bump version to ${{ env.version }}"
